/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/user/order/payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["user_order_payment"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/addressBook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["user_addressBook_update"];
        post: operations["user_addressBook_save"];
        delete: operations["user_addressBook_deleteById"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/addressBook/default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["user_addressBook_getDefault"];
        put: operations["user_addressBook_setDefault"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/shop/{status}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["shop_setStatus"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/setmeal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["setmeal_update"];
        post: operations["setmeal_save"];
        delete: operations["setmeal_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/employee": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["employee_update"];
        post: operations["employee_save"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["dish_update"];
        post: operations["dish_save"];
        delete: operations["dish_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["category_update"];
        post: operations["category_save"];
        delete: operations["category_deleteById"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/user/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["user_user_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/shoppingCart/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["user_shoppingCart_add"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/order/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["user_order_submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/setmeal/status/{status}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["setmeal_changeStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/employee/status/{status}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["employee_changeStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/employee/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["employee_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/employee/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["employee_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dish/status/{status}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["dish_changeStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/common/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["common_upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/category/status/{status}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["category_startOrStop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/shoppingCart/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["user_shoppingCart_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/shop/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["user_shop_getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/setmeal/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["user_setmeal_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/setmeal/dish/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["user_setmeal_dishList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/order/reminder/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["user_order_reminder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/dish/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["user_dish_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/category/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["user_category_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/addressBook/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["user_addressBook_getById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/addressBook/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["user_addressBook_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/workspace/overviewSetmeals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["workspace_setmealOverView"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/workspace/overviewOrders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["workspace_orderOverView"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/workspace/overviewDishes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["workspace_dishOverView"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/workspace/businessData": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["workspace_businessData"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/shop/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["shop_getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/setmeal/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["setmeal_getById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/setmeal/page": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["setmeal_page"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/report/userStatistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["report_userStatistics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/report/turnoverStatistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["report_turnoverStatistics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/report/top10": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["report_top10"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/report/ordersStatistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["report_orderStatistics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/report/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["report_report"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/employee/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["employee_getById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/employee/page": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["employee_page"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dish/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["dish_getById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dish/page": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["dish_page"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dish/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["dish_listByCategoryId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/category/page": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["category_page"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/category/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["category_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/shoppingCart/clean": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["user_shoppingCart_clean"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notify/paySuccess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["payNotify_paySuccessNotify"];
        put: operations["payNotify_paySuccessNotify_2"];
        post: operations["payNotify_paySuccessNotify_1"];
        delete: operations["payNotify_paySuccessNotify_3"];
        options: operations["payNotify_paySuccessNotify_6"];
        head: operations["payNotify_paySuccessNotify_5"];
        patch: operations["payNotify_paySuccessNotify_4"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        OrdersPaymentDTO: {
            orderNumber?: string;
            /** Format: int32 */
            payMethod?: number;
        };
        OrderPaymentVO: {
            nonceStr?: string;
            paySign?: string;
            timeStamp?: string;
            signType?: string;
            packageStr?: string;
        };
        ResultOrderPaymentVO: components["schemas"]["ResultBase"] & {
            data?: components["schemas"]["OrderPaymentVO"];
        };
        AddressBook: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            userId?: number;
            consignee?: string;
            phone?: string;
            sex?: string;
            provinceCode?: string;
            provinceName?: string;
            cityCode?: string;
            cityName?: string;
            districtCode?: string;
            districtName?: string;
            detail?: string;
            label?: string;
            /** Format: int32 */
            isDefault?: number;
        };
        Result: components["schemas"]["ResultBase"] & {
            data?: unknown;
        };
        SetmealDTO: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            categoryId: number;
            name: string;
            price: number;
            /** Format: int32 */
            status: number;
            description: string;
            image: string;
            setmealDishes: components["schemas"]["SetmealDish"][];
        };
        SetmealDish: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            setmealId?: number;
            /** Format: int64 */
            dishId: number;
            name: string;
            price: number;
            /** Format: int32 */
            copies: number;
        };
        EmployeeDTO: {
            /** Format: int64 */
            id?: number;
            username?: string;
            name?: string;
            phone?: string;
            sex?: string;
            idNumber?: string;
        };
        ResultString: components["schemas"]["ResultBase"] & {
            data?: string;
        };
        DishDTO: {
            /** Format: int64 */
            id?: number;
            name: string;
            /** Format: int64 */
            categoryId: number;
            price: number;
            image: string;
            description: string;
            /** Format: int32 */
            status: number;
            flavors: components["schemas"]["DishFlavor"][];
        };
        DishFlavor: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            dishId?: number;
            name?: string;
            value?: string;
        };
        CategoryDTO: {
            /** Format: int64 */
            id?: number;
            /** Format: int32 */
            type: number;
            name: string;
            /** Format: int32 */
            sort: number;
        };
        UserLoginDTO: {
            code?: string;
        };
        ResultUserLoginVO: components["schemas"]["ResultBase"] & {
            data?: components["schemas"]["UserLoginVO"];
        };
        UserLoginVO: {
            /** Format: int64 */
            id?: number;
            openid?: string;
            token?: string;
        };
        ShoppingCartDTO: {
            /** Format: int64 */
            dishId?: number;
            /** Format: int64 */
            setmealId?: number;
            dishFlavor?: string;
        };
        OrdersSubmitDTO: {
            /** Format: int64 */
            addressBookId?: number;
            /** Format: int32 */
            payMethod?: number;
            remark?: string;
            /** Format: date-time */
            estimatedDeliveryTime?: string;
            /** Format: int32 */
            deliveryStatus?: number;
            /** Format: int32 */
            tablewareNumber?: number;
            /** Format: int32 */
            tablewareStatus?: number;
            /** Format: int32 */
            packAmount?: number;
            amount?: number;
        };
        OrderSubmitVO: {
            /** Format: int64 */
            id?: number;
            orderNumber?: string;
            orderAmount?: number;
            /** Format: date-time */
            orderTime?: string;
        };
        ResultOrderSubmitVO: components["schemas"]["ResultBase"] & {
            data?: components["schemas"]["OrderSubmitVO"];
        };
        /** @description 员工登录时传递的数据模型 */
        EmployeeLoginDTO: {
            /** @description 用户名 */
            username?: string;
            /** @description 密码 */
            password?: string;
        };
        /** @description 员工登录返回的数据格式 */
        EmployeeLoginVO: {
            /**
             * Format: int64
             * @description 主键值
             */
            id: number;
            /** @description 用户名 */
            userName: string;
            /** @description 姓名 */
            name: string;
            /** @description jwt令牌 */
            token: string;
        };
        ResultEmployeeLoginVO: components["schemas"]["ResultBase"] & {
            data?: components["schemas"]["EmployeeLoginVO"];
        };
        ResultListShoppingCart: components["schemas"]["ResultBase"] & {
            data?: components["schemas"]["ShoppingCart"][];
        };
        ShoppingCart: {
            /** Format: int64 */
            id?: number;
            name?: string;
            /** Format: int64 */
            userId?: number;
            /** Format: int64 */
            dishId?: number;
            /** Format: int64 */
            setmealId?: number;
            dishFlavor?: string;
            /** Format: int32 */
            number?: number;
            amount?: number;
            image?: string;
            /** Format: date-time */
            createTime?: string;
        };
        ResultListSetmeal: components["schemas"]["ResultBase"] & {
            data?: components["schemas"]["Setmeal"][];
        };
        Setmeal: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            categoryId?: number;
            name?: string;
            price?: number;
            /** Format: int32 */
            status?: number;
            description?: string;
            image?: string;
            /** Format: date-time */
            createTime?: string;
            /** Format: date-time */
            updateTime?: string;
            /** Format: int64 */
            createUser?: number;
            /** Format: int64 */
            updateUser?: number;
        };
        DishItemVO: {
            name?: string;
            /** Format: int32 */
            copies?: number;
            image?: string;
            description?: string;
        };
        ResultListDishItemVO: components["schemas"]["ResultBase"] & {
            data?: components["schemas"]["DishItemVO"][];
        };
        DishVO: {
            /** Format: int64 */
            id: number;
            name: string;
            /** Format: int64 */
            categoryId: number;
            price: number;
            image: string;
            description: string;
            /** Format: int32 */
            status: number;
            /** Format: date-time */
            updateTime: string;
            categoryName: string;
            flavors: components["schemas"]["DishFlavor"][];
        };
        ResultListDishVO: components["schemas"]["ResultBase"] & {
            data?: components["schemas"]["DishVO"][];
        };
        Category: {
            /** Format: int64 */
            id?: number;
            /** Format: int32 */
            type?: number;
            name?: string;
            /** Format: int32 */
            sort?: number;
            /** Format: int32 */
            status?: number;
            /** Format: date-time */
            createTime?: string;
            /** Format: date-time */
            updateTime?: string;
            /** Format: int64 */
            createUser?: number;
            /** Format: int64 */
            updateUser?: number;
        };
        ResultListCategory: components["schemas"]["ResultBase"] & {
            data?: components["schemas"]["Category"][];
        };
        ResultAddressBook: components["schemas"]["ResultBase"] & {
            data?: components["schemas"]["AddressBook"];
        };
        ResultListAddressBook: components["schemas"]["ResultBase"] & {
            data?: components["schemas"]["AddressBook"][];
        };
        ResultSetmealOverViewVO: components["schemas"]["ResultBase"] & {
            data?: components["schemas"]["SetmealOverViewVO"];
        };
        SetmealOverViewVO: {
            /** Format: int32 */
            sold?: number;
            /** Format: int32 */
            discontinued?: number;
        };
        OrderOverViewVO: {
            /** Format: int32 */
            waitingOrders?: number;
            /** Format: int32 */
            deliveredOrders?: number;
            /** Format: int32 */
            completedOrders?: number;
            /** Format: int32 */
            cancelledOrders?: number;
            /** Format: int32 */
            allOrders?: number;
        };
        ResultOrderOverViewVO: components["schemas"]["ResultBase"] & {
            data?: components["schemas"]["OrderOverViewVO"];
        };
        DishOverViewVO: {
            /** Format: int32 */
            sold?: number;
            /** Format: int32 */
            discontinued?: number;
        };
        ResultDishOverViewVO: components["schemas"]["ResultBase"] & {
            data?: components["schemas"]["DishOverViewVO"];
        };
        BusinessDataVO: {
            /** Format: double */
            turnover?: number;
            /** Format: int32 */
            validOrderCount?: number;
            /** Format: double */
            orderCompletionRate?: number;
            /** Format: double */
            unitPrice?: number;
            /** Format: int32 */
            newUsers?: number;
        };
        ResultBusinessDataVO: components["schemas"]["ResultBase"] & {
            data?: components["schemas"]["BusinessDataVO"];
        };
        ResultSetmealVO: components["schemas"]["ResultBase"] & {
            data?: components["schemas"]["SetmealVO"];
        };
        SetmealVO: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            categoryId: number;
            name: string;
            price: number;
            /** Format: int32 */
            status: number;
            description: string;
            image: string;
            /** Format: date-time */
            updateTime: string;
            categoryName: string;
            setmealDishes: components["schemas"]["SetmealDish"][];
        };
        SetmealPageQueryDTO: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            pageSize?: number;
            name?: string;
            /** Format: int32 */
            categoryId?: number;
            /** Format: int32 */
            status?: number;
        };
        PageResultSetmealVO: {
            /** Format: int64 */
            total: number;
            records: components["schemas"]["SetmealVO"][];
        };
        ResultPageResultSetmealVO: components["schemas"]["ResultBase"] & {
            data?: components["schemas"]["PageResultSetmealVO"];
        };
        ResultUserReportVO: components["schemas"]["ResultBase"] & {
            data?: components["schemas"]["UserReportVO"];
        };
        UserReportVO: {
            dateList?: string;
            totalUserList?: string;
            newUserList?: string;
        };
        ResultTurnoverReportVO: components["schemas"]["ResultBase"] & {
            data?: components["schemas"]["TurnoverReportVO"];
        };
        TurnoverReportVO: {
            dateList?: string;
            turnoverList?: string;
        };
        ResultSalesTop10ReportVO: components["schemas"]["ResultBase"] & {
            data?: components["schemas"]["SalesTop10ReportVO"];
        };
        SalesTop10ReportVO: {
            nameList?: string;
            numberList?: string;
        };
        OrderReportVO: {
            dateList?: string;
            orderCountList?: string;
            validOrderCountList?: string;
            /** Format: int32 */
            totalOrderCount?: number;
            /** Format: int32 */
            validOrderCount?: number;
            /** Format: double */
            orderCompletionRate?: number;
        };
        ResultOrderReportVO: components["schemas"]["ResultBase"] & {
            data?: components["schemas"]["OrderReportVO"];
        };
        Employee: {
            /** Format: int64 */
            id: number;
            username: string;
            name: string;
            password: string;
            phone: string;
            sex: string;
            idNumber: string;
            /** Format: int32 */
            status: number;
            /** Format: date-time */
            createTime: string;
            /** Format: date-time */
            updateTime: string;
            /** Format: int64 */
            createUser: number;
            /** Format: int64 */
            updateUser: number;
        };
        ResultEmployee: components["schemas"]["ResultBase"] & {
            data?: components["schemas"]["Employee"];
        };
        EmployeePageQueryDTO: {
            name?: string;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            pageSize?: number;
        };
        PageResultEmployee: {
            /** Format: int64 */
            total: number;
            records: components["schemas"]["Employee"][];
        };
        ResultPageResultEmployee: components["schemas"]["ResultBase"] & {
            data?: components["schemas"]["PageResultEmployee"];
        };
        ResultDishVO: components["schemas"]["ResultBase"] & {
            data?: components["schemas"]["DishVO"];
        };
        DishPageQueryDTO: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            pageSize?: number;
            name?: string;
            /** Format: int32 */
            categoryId?: number;
            /** Format: int32 */
            status?: number;
        };
        PageResultDishVO: {
            /** Format: int64 */
            total: number;
            records: components["schemas"]["DishVO"][];
        };
        ResultPageResultDishVO: components["schemas"]["ResultBase"] & {
            data?: components["schemas"]["PageResultDishVO"];
        };
        Dish: {
            /** Format: int64 */
            id: number;
            name: string;
            /** Format: int64 */
            categoryId?: number;
            price: number;
            image?: string;
            description?: string;
            /** Format: int32 */
            status: number;
            /** Format: date-time */
            createTime?: string;
            /** Format: date-time */
            updateTime?: string;
            /** Format: int64 */
            createUser?: number;
            /** Format: int64 */
            updateUser?: number;
        };
        ResultListDish: components["schemas"]["ResultBase"] & {
            data?: components["schemas"]["Dish"][];
        };
        CategoryPageQueryDTO: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            pageSize?: number;
            name?: string;
            /** Format: int32 */
            type?: number;
        };
        PageResultCategory: {
            /** Format: int64 */
            total: number;
            records: components["schemas"]["Category"][];
        };
        ResultPageResultCategory: components["schemas"]["ResultBase"] & {
            data?: components["schemas"]["PageResultCategory"];
        };
        ResultBase: {
            /** Format: int32 */
            code?: number;
            msg?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    user_order_payment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrdersPaymentDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultOrderPaymentVO"];
                };
            };
        };
    };
    user_addressBook_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddressBook"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Result"];
                };
            };
        };
    };
    user_addressBook_save: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddressBook"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Result"];
                };
            };
        };
    };
    user_addressBook_deleteById: {
        parameters: {
            query: {
                id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Result"];
                };
            };
        };
    };
    user_addressBook_getDefault: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultAddressBook"];
                };
            };
        };
    };
    user_addressBook_setDefault: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddressBook"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Result"];
                };
            };
        };
    };
    shop_setStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                status: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Result"];
                };
            };
        };
    };
    setmeal_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetmealDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Result"];
                };
            };
        };
    };
    setmeal_save: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetmealDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Result"];
                };
            };
        };
    };
    setmeal_delete: {
        parameters: {
            query: {
                ids: number[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Result"];
                };
            };
        };
    };
    employee_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultString"];
                };
            };
        };
    };
    employee_save: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Result"];
                };
            };
        };
    };
    dish_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DishDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Result"];
                };
            };
        };
    };
    dish_save: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DishDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Result"];
                };
            };
        };
    };
    dish_delete: {
        parameters: {
            query: {
                ids: number[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Result"];
                };
            };
        };
    };
    category_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultString"];
                };
            };
        };
    };
    category_save: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultString"];
                };
            };
        };
    };
    category_deleteById: {
        parameters: {
            query: {
                id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultString"];
                };
            };
        };
    };
    user_user_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLoginDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultUserLoginVO"];
                };
            };
        };
    };
    user_shoppingCart_add: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShoppingCartDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Result"];
                };
            };
        };
    };
    user_order_submit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrdersSubmitDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultOrderSubmitVO"];
                };
            };
        };
    };
    setmeal_changeStatus: {
        parameters: {
            query: {
                id: number;
            };
            header?: never;
            path: {
                status: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultString"];
                };
            };
        };
    };
    employee_changeStatus: {
        parameters: {
            query: {
                id: number;
            };
            header?: never;
            path: {
                status: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultString"];
                };
            };
        };
    };
    employee_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultString"];
                };
            };
        };
    };
    employee_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeLoginDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultEmployeeLoginVO"];
                };
            };
        };
    };
    dish_changeStatus: {
        parameters: {
            query: {
                id: number;
            };
            header?: never;
            path: {
                status: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultString"];
                };
            };
        };
    };
    common_upload: {
        parameters: {
            query: {
                file: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultString"];
                };
            };
        };
    };
    category_startOrStop: {
        parameters: {
            query: {
                id: number;
            };
            header?: never;
            path: {
                status: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultString"];
                };
            };
        };
    };
    user_shoppingCart_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultListShoppingCart"];
                };
            };
        };
    };
    user_shop_getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Result"];
                };
            };
        };
    };
    user_setmeal_list: {
        parameters: {
            query: {
                categoryId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultListSetmeal"];
                };
            };
        };
    };
    user_setmeal_dishList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultListDishItemVO"];
                };
            };
        };
    };
    user_order_reminder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Result"];
                };
            };
        };
    };
    user_dish_list: {
        parameters: {
            query: {
                categoryId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultListDishVO"];
                };
            };
        };
    };
    user_category_list: {
        parameters: {
            query: {
                type: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultListCategory"];
                };
            };
        };
    };
    user_addressBook_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultAddressBook"];
                };
            };
        };
    };
    user_addressBook_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultListAddressBook"];
                };
            };
        };
    };
    workspace_setmealOverView: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultSetmealOverViewVO"];
                };
            };
        };
    };
    workspace_orderOverView: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultOrderOverViewVO"];
                };
            };
        };
    };
    workspace_dishOverView: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultDishOverViewVO"];
                };
            };
        };
    };
    workspace_businessData: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultBusinessDataVO"];
                };
            };
        };
    };
    shop_getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Result"];
                };
            };
        };
    };
    setmeal_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultSetmealVO"];
                };
            };
        };
    };
    setmeal_page: {
        parameters: {
            query: {
                setmealPageQueryDTO: components["schemas"]["SetmealPageQueryDTO"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultPageResultSetmealVO"];
                };
            };
        };
    };
    report_userStatistics: {
        parameters: {
            query: {
                begin: string;
                end: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultUserReportVO"];
                };
            };
        };
    };
    report_turnoverStatistics: {
        parameters: {
            query: {
                begin: string;
                end: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultTurnoverReportVO"];
                };
            };
        };
    };
    report_top10: {
        parameters: {
            query: {
                begin: string;
                end: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultSalesTop10ReportVO"];
                };
            };
        };
    };
    report_orderStatistics: {
        parameters: {
            query: {
                begin: string;
                end: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultOrderReportVO"];
                };
            };
        };
    };
    report_report: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    employee_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultEmployee"];
                };
            };
        };
    };
    employee_page: {
        parameters: {
            query: {
                employeePageQueryDTO: components["schemas"]["EmployeePageQueryDTO"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultPageResultEmployee"];
                };
            };
        };
    };
    dish_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultDishVO"];
                };
            };
        };
    };
    dish_page: {
        parameters: {
            query: {
                dishPageQueryDTO: components["schemas"]["DishPageQueryDTO"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultPageResultDishVO"];
                };
            };
        };
    };
    dish_listByCategoryId: {
        parameters: {
            query: {
                categoryId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultListDish"];
                };
            };
        };
    };
    category_page: {
        parameters: {
            query: {
                categoryPageQueryDTO: components["schemas"]["CategoryPageQueryDTO"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultPageResultCategory"];
                };
            };
        };
    };
    category_list: {
        parameters: {
            query: {
                type: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultListCategory"];
                };
            };
        };
    };
    user_shoppingCart_clean: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Result"];
                };
            };
        };
    };
    payNotify_paySuccessNotify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    payNotify_paySuccessNotify_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    payNotify_paySuccessNotify_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    payNotify_paySuccessNotify_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    payNotify_paySuccessNotify_6: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    payNotify_paySuccessNotify_5: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    payNotify_paySuccessNotify_4: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
